image: python:slim-bookworm

stages:
  - test
  - deploy

test:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
  script:
  - pip install -r requirements.txt && mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
  before_script:
    - pip install -r requirements.txt
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo $SSH_PRIVATE_KEY | base64 -d
  script:
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdocs build --strict --verbose && scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./docs/** \
    $USERNAME@$HOST:/mnt/nvme/k3s/webserver/html/docs/
  artifacts:
    paths:
    - docs
